Repository zbqmgldjfh/issue-tracker, pull requests merged in 2022-06, with the labels that each got.

#5 Feat/create entity #4 merge
  BE/src/main/java/codesquad/shine/issuetracker/IssueTrackerApplication.java
  BE/src/main/java/codesquad/shine/issuetracker/comment/domain/Comment.java
  BE/src/main/java/codesquad/shine/issuetracker/common/imbeddable/BaseTimeEntity.java
  BE/src/main/java/codesquad/shine/issuetracker/issue/domain/Issue.java
  BE/src/main/java/codesquad/shine/issuetracker/issue/domain/IssueAssignee.java
  BE/src/main/java/codesquad/shine/issuetracker/issue/domain/IssueLabel.java
  BE/src/main/java/codesquad/shine/issuetracker/label/domain/Color.java
  BE/src/main/java/codesquad/shine/issuetracker/label/domain/Label.java
  BE/src/main/java/codesquad/shine/issuetracker/milestone/domain/Milestone.java
  BE/src/main/java/codesquad/shine/issuetracker/photo/domain/Photo.java
  BE/src/main/java/codesquad/shine/issuetracker/user/domain/User.java
Labels: feat, BE

#7 Feat/oauth login #6 merge
  BE/build.gradle
  BE/src/main/java/codesquad/shine/issuetracker/auth/AuthClient.java
  BE/src/main/java/codesquad/shine/issuetracker/auth/AuthController.java
  BE/src/main/java/codesquad/shine/issuetracker/auth/AuthService.java
  BE/src/main/java/codesquad/shine/issuetracker/auth/InMemoryProviderRepository.java
  BE/src/main/java/codesquad/shine/issuetracker/auth/JwtTokenFactory.java
  BE/src/main/java/codesquad/shine/issuetracker/auth/OAuthAdapter.java
  BE/src/main/java/codesquad/shine/issuetracker/auth/OAuthProperties.java
  BE/src/main/java/codesquad/shine/issuetracker/auth/OAuthProvider.java
  BE/src/main/java/codesquad/shine/issuetracker/auth/OAuthToken.java
  BE/src/main/java/codesquad/shine/issuetracker/auth/OAuthUser.java
  BE/src/main/java/codesquad/shine/issuetracker/auth/dto/LoginResponse.java
  BE/src/main/java/codesquad/shine/issuetracker/auth/github/GithubAuthClient.java
  BE/src/main/java/codesquad/shine/issuetracker/auth/github/GithubToken.java
  BE/src/main/java/codesquad/shine/issuetracker/auth/interceptor/AuthenticationInterceptor.java
  BE/src/main/java/codesquad/shine/issuetracker/config/OAuthConfig.java
  BE/src/main/java/codesquad/shine/issuetracker/config/WebConfig.java
  BE/src/main/java/codesquad/shine/issuetracker/exception/ErrorCode.java
  BE/src/main/java/codesquad/shine/issuetracker/exception/unchecked/BusinessException.java
  BE/src/main/java/codesquad/shine/issuetracker/exception/unchecked/NotAvailableException.java
  BE/src/main/java/codesquad/shine/issuetracker/exception/unchecked/NotFoundException.java
  BE/src/main/java/codesquad/shine/issuetracker/user/domain/User.java
  BE/src/main/java/codesquad/shine/issuetracker/user/domain/UserRepository.java
  BE/src/main/resources/application-local.yml
  BE/src/main/resources/application.yml
Labels: feat, BE

#11 chore: 환경설정 완료
  frontend/.eslintrc
  frontend/.prettierrc
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/tsconfig.json
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: FE, chore

#15 feat: 로그인 페이지 UI 구현
  frontend/.eslintrc
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Login.styled.ts
  frontend/src/components/Login.tsx
  frontend/src/index.tsx
  frontend/src/pages/LoginPage.styled.ts
  frontend/src/pages/LoginPage.tsx
  frontend/src/styles/globalStyle.ts
  frontend/src/utils/utils.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: feat, FE

#26 feat: Header 컴포넌트와 이슈 페이지 UI 완성
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/Actions.svg
  frontend/src/assets/Bell.svg
  frontend/src/assets/ClosedIssues.svg
  frontend/src/assets/Code.svg
  frontend/src/assets/DropdownCaret.svg
  frontend/src/assets/Fork.svg
  frontend/src/assets/Github.svg
  frontend/src/assets/Insights.svg
  frontend/src/assets/Issues.svg
  frontend/src/assets/Label.svg
  frontend/src/assets/Milestone.svg
  frontend/src/assets/OpenIssues.svg
  frontend/src/assets/Plus.svg
  frontend/src/assets/Projects.svg
  frontend/src/assets/PullRequests.svg
  frontend/src/assets/Repository.svg
  frontend/src/assets/Review.svg
  frontend/src/assets/Security.svg
  frontend/src/assets/Star.svg
  frontend/src/assets/Watch.svg
  frontend/src/assets/Wiki.svg
  frontend/src/common/GlobalStyle.ts
  frontend/src/components/Login.styled.ts
  frontend/src/components/Login.tsx
  frontend/src/components/common/dropdownButton/DropdownButton.styled.ts
  frontend/src/components/common/dropdownButton/DropdownButton.tsx
  frontend/src/components/common/header/Header.styled.ts
  frontend/src/components/common/header/Header.tsx
  frontend/src/components/common/issueAttribute/IssueAttribute.styled.ts
  frontend/src/components/common/issueAttribute/IssueAttribute.tsx
  frontend/src/components/common/itemsNumber/itemsNumber.styled.ts
  frontend/src/components/common/itemsNumber/itemsNumber.tsx
  frontend/src/components/common/repositoryHeader/RepositoryHeader.styled.ts
  frontend/src/components/common/repositoryHeader/RepositoryHeader.tsx
  frontend/src/components/common/repositoryHeader/navArea/NavArea.styled.ts
  frontend/src/components/common/repositoryHeader/navArea/NavArea.tsx
  frontend/src/components/issues/IssuesHeader.styled.ts
  frontend/src/components/issues/IssuesHeader.tsx
  frontend/src/components/issues/IssuesItem.styled.ts
  frontend/src/components/issues/IssuesItem.tsx
  frontend/src/components/issues/IssuesMain.styled.ts
  frontend/src/components/issues/IssuesMain.tsx
  frontend/src/components/issues/IssuesToolbar.styled.ts
  frontend/src/components/issues/IssuesToolbar.tsx
  frontend/src/custom.d.ts
  frontend/src/pages/header/HeaderPage.styled.ts
  frontend/src/pages/header/HeaderPage.tsx
  frontend/src/pages/issues/IssuesPage.styled.ts
  frontend/src/pages/issues/IssuesPage.tsx
  frontend/src/pages/login/LoginPage.styled.ts
  frontend/src/pages/login/LoginPage.tsx
  frontend/tsconfig.json
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: feat, design, FE

#27 [FE] 새로운 이슈 작성 컴포넌트 구현
  frontend/.eslintrc
  frontend/src/components/commentArea/CommentArea.styled.ts
  frontend/src/components/commentArea/CommentArea.tsx
  frontend/src/components/commentArea/CommentHeader.styled.ts
  frontend/src/components/commentArea/CommentHeader.tsx
  frontend/src/components/fileAttachButton/FileAttachButton.styled.ts
  frontend/src/components/fileAttachButton/FileAttachButton.tsx
  frontend/src/components/issueSideBarForm/IssueSideBarForm.styled.ts
  frontend/src/components/issueSideBarForm/IssueSideBarForm.tsx
  frontend/src/components/submitButton/SubmitButton.styled.ts
  frontend/src/components/submitButton/SubmitButton.tsx
  frontend/src/components/title/Title.styled.ts
  frontend/src/components/title/Title.tsx
  frontend/src/pages/addIssuePage/AddIssuePage.styled.ts
  frontend/src/pages/addIssuePage/AddIssuePage.tsx
Labels: feat, FE

#42 [FE] 로딩 페이지 구현
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/loading.gif
  frontend/src/components/login/Login.styled.ts
  frontend/src/components/login/Login.tsx
  frontend/src/custom.d.ts
  frontend/src/pages/loading/LoadingPage.styled.ts
  frontend/src/pages/loading/LoadingPage.tsx
  frontend/src/pages/login/LoginPage.tsx
  frontend/yarn.lock
Labels: FE

#43 feat: Redux 이용해서 tab 상태관리 적용
  frontend/.eslintrc
  frontend/package.json
  frontend/src/assets/Close.svg
  frontend/src/components/common/dropdownButton/DropdownButton.tsx
  frontend/src/components/issues/DropdownButton.styled.ts
  frontend/src/components/issues/DropdownButton.tsx
  frontend/src/components/issues/DropdownMenu.styled.ts
  frontend/src/components/issues/DropdownMenu.tsx
  frontend/src/components/issues/IssuesToolbar.styled.ts
  frontend/src/components/issues/IssuesToolbar.tsx
  frontend/src/custom.d.ts
  frontend/src/index.tsx
  frontend/src/modules/clickedTab.ts
  frontend/yarn.lock
Labels: feat, FE

#60 [FE] 로그인 연동
  frontend/src/constants/constant.ts
  frontend/src/pages/loading/LoadingPage.tsx
Labels: FE

#62 [FE] useOutsideClick 적용
  frontend/src/App.tsx
  frontend/src/components/commentArea/CommentHeader.tsx
  frontend/src/components/issueModal/IssueModal.tsx
  frontend/src/components/issueSideBarForm/IssueSideBarForm.tsx
  frontend/src/components/issues/IssuesItem.tsx
  frontend/src/components/issues/IssuesMain.tsx
  frontend/src/hooks/useOutsideClick.ts
  frontend/src/pages/createIssuePage/CreateIssuePage.tsx
  frontend/src/utils/utils.ts
Labels: FE

#64 [FE] 이슈리스트 서버 연동
  frontend/src/components/issues/IssuesMain.tsx
  frontend/src/components/issues/IssuesToolbar.tsx
  frontend/src/constants/constant.ts
Labels: FE
